
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_CHAVE FECHA_CHAVE ID_VARIAVEL KW_ATIVIDADES KW_CUSTO KW_DONO KW_FIM KW_INICIO KW_NOME KW_PROCESSO KW_RESPONSAVEL KW_SEGUINTE KW_TEMPO KW_TIPO LIT_STRING NUMERO OP_ATRIBUICAO PONTO_VIRGULA SETA VIRGULAprograma : processoprocesso : KW_PROCESSO ABRE_CHAVE definicoes_processo FECHA_CHAVEdefinicoes_processo : prop_nome prop_dono prop_inicio bloco_atividades prop_fimprop_nome : KW_NOME OP_ATRIBUICAO LIT_STRING PONTO_VIRGULAprop_dono : KW_DONO OP_ATRIBUICAO LIT_STRING PONTO_VIRGULAprop_inicio : KW_INICIO OP_ATRIBUICAO ID_VARIAVEL PONTO_VIRGULAprop_fim : KW_FIM OP_ATRIBUICAO LIT_STRING PONTO_VIRGULAbloco_atividades : KW_ATIVIDADES ABRE_CHAVE lista_atividades FECHA_CHAVElista_atividades : lista_atividades atividade\n| emptyatividade : ID_VARIAVEL ABRE_CHAVE lista_propriedades_atividade FECHA_CHAVElista_propriedades_atividade : propriedade_atividade lista_propriedades_atividade\n| emptypropriedade_atividade : prop_nome \n| prop_tipo\n| prop_responsavel\n| prop_tempo\n| prop_custo\n| prop_seguinteprop_tipo : KW_TIPO OP_ATRIBUICAO LIT_STRING PONTO_VIRGULAprop_responsavel : KW_RESPONSAVEL OP_ATRIBUICAO LIT_STRING PONTO_VIRGULAprop_tempo : KW_TEMPO OP_ATRIBUICAO NUMERO PONTO_VIRGULAprop_custo : KW_CUSTO OP_ATRIBUICAO NUMERO PONTO_VIRGULAprop_seguinte : KW_SEGUINTE OP_ATRIBUICAO ABRE_CHAVE lista_fluxos FECHA_CHAVE PONTO_VIRGULAflow_target : ID_VARIAVEL\n| KW_FIMlista_fluxos : fluxo_condicional lista_fluxos_continua\n| flow_targetfluxo_condicional : ID_VARIAVEL SETA flow_targetlista_fluxos_continua : VIRGULA fluxo_condicional lista_fluxos_continua\n| emptyempty :'
    
_lr_action_items = {'KW_PROCESSO':([0,],[3,]),'$end':([1,2,8,],[0,-1,-2,]),'ABRE_CHAVE':([3,17,33,56,],[4,23,35,61,]),'KW_NOME':([4,20,35,37,39,40,41,42,43,44,62,63,64,65,76,],[7,-4,7,7,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,]),'FECHA_CHAVE':([5,20,21,23,27,28,32,34,35,36,37,38,39,40,41,42,43,44,50,51,62,63,64,65,66,67,68,69,70,72,74,76,77,79,80,81,],[8,-4,-3,-32,31,-10,-9,-7,-32,50,-32,-13,-14,-15,-16,-17,-18,-19,-11,-12,-20,-21,-22,-23,71,-32,-28,-25,-26,-27,-31,-24,-32,-25,-29,-30,]),'KW_DONO':([6,20,],[10,-4,]),'OP_ATRIBUICAO':([7,10,13,22,45,46,47,48,49,],[11,14,18,26,52,53,54,55,56,]),'KW_INICIO':([9,25,],[13,-5,]),'LIT_STRING':([11,14,26,52,53,],[15,19,30,57,58,]),'KW_ATIVIDADES':([12,29,],[17,-6,]),'PONTO_VIRGULA':([15,19,24,30,57,58,59,60,71,],[20,25,29,34,62,63,64,65,76,]),'KW_FIM':([16,31,61,75,],[22,-8,70,70,]),'ID_VARIAVEL':([18,23,27,28,32,50,61,73,75,],[24,-32,33,-10,-9,-11,69,78,79,]),'KW_TIPO':([20,35,37,39,40,41,42,43,44,62,63,64,65,76,],[-4,45,45,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,]),'KW_RESPONSAVEL':([20,35,37,39,40,41,42,43,44,62,63,64,65,76,],[-4,46,46,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,]),'KW_TEMPO':([20,35,37,39,40,41,42,43,44,62,63,64,65,76,],[-4,47,47,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,]),'KW_CUSTO':([20,35,37,39,40,41,42,43,44,62,63,64,65,76,],[-4,48,48,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,]),'KW_SEGUINTE':([20,35,37,39,40,41,42,43,44,62,63,64,65,76,],[-4,49,49,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,]),'NUMERO':([54,55,],[59,60,]),'VIRGULA':([67,70,77,79,80,],[73,-26,73,-25,-29,]),'SETA':([69,78,],[75,75,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'processo':([0,],[2,]),'definicoes_processo':([4,],[5,]),'prop_nome':([4,35,37,],[6,39,39,]),'prop_dono':([6,],[9,]),'prop_inicio':([9,],[12,]),'bloco_atividades':([12,],[16,]),'prop_fim':([16,],[21,]),'lista_atividades':([23,],[27,]),'empty':([23,35,37,67,77,],[28,38,38,74,74,]),'atividade':([27,],[32,]),'lista_propriedades_atividade':([35,37,],[36,51,]),'propriedade_atividade':([35,37,],[37,37,]),'prop_tipo':([35,37,],[40,40,]),'prop_responsavel':([35,37,],[41,41,]),'prop_tempo':([35,37,],[42,42,]),'prop_custo':([35,37,],[43,43,]),'prop_seguinte':([35,37,],[44,44,]),'lista_fluxos':([61,],[66,]),'fluxo_condicional':([61,73,],[67,77,]),'flow_target':([61,75,],[68,80,]),'lista_fluxos_continua':([67,77,],[72,81,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> processo','programa',1,'p_programa','parser.py',9),
  ('processo -> KW_PROCESSO ABRE_CHAVE definicoes_processo FECHA_CHAVE','processo',4,'p_processo','parser.py',13),
  ('definicoes_processo -> prop_nome prop_dono prop_inicio bloco_atividades prop_fim','definicoes_processo',5,'p_definicoes_processo','parser.py',17),
  ('prop_nome -> KW_NOME OP_ATRIBUICAO LIT_STRING PONTO_VIRGULA','prop_nome',4,'p_prop_nome','parser.py',32),
  ('prop_dono -> KW_DONO OP_ATRIBUICAO LIT_STRING PONTO_VIRGULA','prop_dono',4,'p_prop_dono','parser.py',36),
  ('prop_inicio -> KW_INICIO OP_ATRIBUICAO ID_VARIAVEL PONTO_VIRGULA','prop_inicio',4,'p_prop_inicio','parser.py',40),
  ('prop_fim -> KW_FIM OP_ATRIBUICAO LIT_STRING PONTO_VIRGULA','prop_fim',4,'p_prop_fim','parser.py',44),
  ('bloco_atividades -> KW_ATIVIDADES ABRE_CHAVE lista_atividades FECHA_CHAVE','bloco_atividades',4,'p_bloco_atividades','parser.py',53),
  ('lista_atividades -> lista_atividades atividade','lista_atividades',2,'p_lista_atividades','parser.py',57),
  ('lista_atividades -> empty','lista_atividades',1,'p_lista_atividades','parser.py',58),
  ('atividade -> ID_VARIAVEL ABRE_CHAVE lista_propriedades_atividade FECHA_CHAVE','atividade',4,'p_atividade','parser.py',66),
  ('lista_propriedades_atividade -> propriedade_atividade lista_propriedades_atividade','lista_propriedades_atividade',2,'p_lista_propriedades_atividade','parser.py',75),
  ('lista_propriedades_atividade -> empty','lista_propriedades_atividade',1,'p_lista_propriedades_atividade','parser.py',76),
  ('propriedade_atividade -> prop_nome','propriedade_atividade',1,'p_propriedade_atividade','parser.py',83),
  ('propriedade_atividade -> prop_tipo','propriedade_atividade',1,'p_propriedade_atividade','parser.py',84),
  ('propriedade_atividade -> prop_responsavel','propriedade_atividade',1,'p_propriedade_atividade','parser.py',85),
  ('propriedade_atividade -> prop_tempo','propriedade_atividade',1,'p_propriedade_atividade','parser.py',86),
  ('propriedade_atividade -> prop_custo','propriedade_atividade',1,'p_propriedade_atividade','parser.py',87),
  ('propriedade_atividade -> prop_seguinte','propriedade_atividade',1,'p_propriedade_atividade','parser.py',88),
  ('prop_tipo -> KW_TIPO OP_ATRIBUICAO LIT_STRING PONTO_VIRGULA','prop_tipo',4,'p_prop_tipo','parser.py',94),
  ('prop_responsavel -> KW_RESPONSAVEL OP_ATRIBUICAO LIT_STRING PONTO_VIRGULA','prop_responsavel',4,'p_prop_responsavel','parser.py',98),
  ('prop_tempo -> KW_TEMPO OP_ATRIBUICAO NUMERO PONTO_VIRGULA','prop_tempo',4,'p_prop_tempo','parser.py',102),
  ('prop_custo -> KW_CUSTO OP_ATRIBUICAO NUMERO PONTO_VIRGULA','prop_custo',4,'p_prop_custo','parser.py',106),
  ('prop_seguinte -> KW_SEGUINTE OP_ATRIBUICAO ABRE_CHAVE lista_fluxos FECHA_CHAVE PONTO_VIRGULA','prop_seguinte',6,'p_prop_seguinte','parser.py',110),
  ('flow_target -> ID_VARIAVEL','flow_target',1,'p_flow_target','parser.py',119),
  ('flow_target -> KW_FIM','flow_target',1,'p_flow_target','parser.py',120),
  ('lista_fluxos -> fluxo_condicional lista_fluxos_continua','lista_fluxos',2,'p_lista_fluxos','parser.py',125),
  ('lista_fluxos -> flow_target','lista_fluxos',1,'p_lista_fluxos','parser.py',126),
  ('fluxo_condicional -> ID_VARIAVEL SETA flow_target','fluxo_condicional',3,'p_fluxo_condicional','parser.py',136),
  ('lista_fluxos_continua -> VIRGULA fluxo_condicional lista_fluxos_continua','lista_fluxos_continua',3,'p_lista_fluxos_continua','parser.py',142),
  ('lista_fluxos_continua -> empty','lista_fluxos_continua',1,'p_lista_fluxos_continua','parser.py',143),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',150),
]
